# Generated by Django 3.2.23 on 2024-01-18 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm_app', '0002_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
